### ISSUE TITLE
[WIP] Enhancement: Add comprehensive documentation with Mkdocs

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/deffcode#1]
## Detailed Description
This issue will track, search and attempt to integrate  a beautiful, static documentation site based on MkDocs which will then be hosted on GitHub Pages. The base Mkdocs docs will implemented along with third-party elegant & simplistic `mkdocs-material` theme. Furthermore, the docs will be build and deployed automatically on gh-pages through GitHub Actions workflow. Also, this enhancement will introduce new Docs related updates like new brand logo, gifs, etc. assets to bring standard and quality to Docs visual design.

### Roadmap:
- [ ] Implemented a beautiful, static documentation site based on **MkDocs** which will then be hosted on GitHub Pages.
- [ ] Crafted base mkdocs with third-party elegant `mkdocs-material` theme.
- [ ] Implement new `mkdocs.yml` with relevant data.
- [ ] Add new `docs` folder to handle markdown pages and its assets.
- [ ] Add new markdown to docs folder, with carefully crafted documents.
- [ ] Add navigation under sections for easily accessing each document.
- [ ] Add new assets like gifs, images, custom scripts, favicons, site.webmanifest for bringing standard and quality to Docs visual design.
- [ ] Revamp new logo and banner for Deffcode Docs.
- [ ] Deploy all assets under separate Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License.
- [ ] Add support for all pymarkdown-extensions.
- [ ] Add support for some important `admonition`, `attr_list`, `codehilite`, `def_list`, `footnotes`, `meta`, and `toc` like Mkdocs extensions.
- [ ] Add support for `mkdocstrings` plugin for auto-built API references.
  * Add python handler for parsing python source-code to `mkdocstrings`.
  * Improv source-code docs for compatibility with `mkdocstrings`.
- [ ] Add changelog with `changelog.md` and contribution guidelines with `contribution.md` in docs.
- [ ] Enabled search and git-revision-date-localized plugins support.
- [ ] Implemented automated Deployment on gh-pages through GitHub Actions workflow.
  * Add new workflow yaml for automated docs deployment.
  * Add complete python dependencies and environment.
  * Add `master` branch to build matrix.
- [ ] Updated Readme.md, Issue and PR templates with new information and updates.
- [ ] Added support for `en` (English) language.
- [ ] Fix any typos and bugs.

### Context

This issue will oversee implementation of Deffcode Docs to with a beautiful, static documentation site based on MkDocs which will then be hosted on GitHub Pages. The base Mkdocs docs will implemented along with third-party elegant & simplistic `mkdocs-material` theme. 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Any Other Important Information

- [MkDocs](https://www.mkdocs.org/) - **Theme:** [mkdocs-material](https://github.com/squidfunk/mkdocs-material)
