### ISSUE TITLE
Enhancement: New default Deffcode project templates 

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/deffcode#2]
## Detailed Description
This issue will track creation of new default Issue and PR Templates for contributing to Deffcode with the latest format available.

## Roadmap
- [x] Add new issue templates: 
  - bug report
  - feature request
  - question 
- [x] Add new PR Template
- [x] Add Deffcode Community Support
- [x] Follow latest GitHub formatting

### Context

This issue will oversee implementation of new customized Issue and PR templates that are available for contributors to use when they open new issues in your repository.

### Any Other Important Information

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
