### ISSUE TITLE
Enhancement: Implement pytest unit tests, coverage, and Continous Integration 

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/deffcode#3]
## Detailed Description
This issue will track implementation of [pytest](https://docs.pytest.org/en/7.0.x/) unit tests, coverage reports, flake8 tests, and automated CI validation on different environments.

## Roadmap
- [x] Add comprehensive pytest unit tests for each case. 
- [x] Add Bash script for dataset download for unit test.
- [ ] Add GitHub Action CI support for Linux-based Testing Envs.
- [ ] Add Appveyor CI support for Windows-based Testing Envs.
- [ ] Add Azure Pipeline CI support for MacOS-based Testing Envs.
- [ ] Add and configure various yamls.
  * auto-handle prerequisites installation, testing, and coverage report uploading.
- [ ] Add code coverage through codecov measures tests effectiveness.
- [ ] Add flake8 testing to discover any anomalies in code.
- [ ] Add badges to Readme.md
- [ ] Fix any related bugs.

### Context

This issue will oversee implementation of pytest unit tests, coverage, and Continous Integration essential for stable working of Deffcode on different OSes and environments. 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
