### ISSUE TITLE
Enhancement: Add metadata extraction and updation support

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/deffcode#4]
## Detailed Description
This issue will implement source metadata extraction and updation support through python's builtin [`@property`](https://docs.python.org/3/library/functions.html#property) decorator which makes usage of getter and setters much easier in Object-Oriented Programming.

## Roadmap
- [ ] Add `metadata` property object function to FFdecoder API
  - The property object will retrieve source metadata form Sourcer API as dict and convert it into JSON dump for pretty printing.
- [ ] Add `metadata` property object with `setter()` method for updating source metadata with user-defined dictionary.
- [ ] Add `retrieve_metadata` class method to Sourcer API.
  - The `retrieve_metadata` will returns Source metadata as python dictionary.
- [ ] Move FFmpeg path validation and handling to Sourcer API.

### Context

This issue will oversee implementation source metadata extraction and updation support through python `@property` decorator.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
