### ISSUE TITLE
Enhancement: Deploy docs to GitHub Pages using GitHub Actions

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/deffcode#7]
## Detailed Description
This issue will track implementation of automated deployment of docs to GitHub Pages using GitHub Actions.

### Roadmap 
- [ ] Implement automated Deployment on `gh-pages` through GitHub Actions workflow:
  - Add new workflow yaml for automated docs deployment.
  - Add complete python dependencies and environment.
  - Add `master` branch on Ubuntu machine to build matrix.
- [ ] Add Docs Versioning:
  - Implemented Docs versioning through mike API.
  - Separate new workflow steps to handle different versions.
  - Update docs deploy workflow to support `latest`, `release` and `dev` builds.
  - Add automatic version extraction from GitHub events.

### Context

This issue will oversee implementation of automated deployment of docs to GitHub Pages which for hosting using GitHub Actions. 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
